{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/runviewer.json"}, "html": {"href": "#!/labscript_suite/runviewer"}, "avatar": {"href": "data/bytebucket.org/ravatar/{71215673-ad3e-425c-ae04-84cc6c2ca7da}ts=445022"}}, "type": "repository", "name": "runviewer", "full_name": "labscript_suite/runviewer", "uuid": "{71215673-ad3e-425c-ae04-84cc6c2ca7da}"}, "links": {"attachments": {"href": "data/repositories/labscript_suite/runviewer/issues/23/attachments_page=1.json"}, "self": {"href": "data/repositories/labscript_suite/runviewer/issues/23.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/runviewer/issues/23/watch"}, "comments": {"href": "data/repositories/labscript_suite/runviewer/issues/23/comments_page=1.json"}, "html": {"href": "#!/labscript_suite/runviewer/issues/23/latest-version-is-incompatible-with-pyqt4"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/labscript_suite/runviewer/issues/23/vote"}}, "reporter": {"display_name": "Shaun Johnstone", "uuid": "{652df738-313d-472c-b7b5-a3f8f98a3322}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D"}, "html": {"href": "https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/38984f1761fc67ce892911496abee619d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSJ-3.png"}}, "nickname": "shjohnst", "type": "user", "account_id": "557058:1b9a15fb-8e4f-407e-b7b9-567c5e1fa1b4"}, "title": "Latest version is incompatible with PyQt4", "component": null, "votes": 0, "watches": 1, "content": {"raw": "It turns out that I only tested the markers pull request #9 on a computer with PyQt5.\r\n\r\nI just tried using it on a computer still running PyQt4 and it crashed (sorry, didn't think to save the error message, something about not being able to check a NoneType or similar). Updating to PyQt5 resolved this.\r\n\r\nWe should either officially cut support for PyQt4 (i.e. don't try to import it, and if it's there but PyQt5 isn't, print a message advising the user to upgrade), or fix the code to be backwards compatible.", "markup": "markdown", "html": "<p>It turns out that I only tested the markers <a href=\"#!/labscript_suite/runviewer/pull-requests/9/markers\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #9</a> on a computer with PyQt5.</p>\n<p>I just tried using it on a computer still running PyQt4 and it crashed (sorry, didn't think to save the error message, something about not being able to check a NoneType or similar). Updating to PyQt5 resolved this.</p>\n<p>We should either officially cut support for PyQt4 (i.e. don't try to import it, and if it's there but PyQt5 isn't, print a message advising the user to upgrade), or fix the code to be backwards compatible.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-05-09T07:31:02.766278+00:00", "milestone": null, "updated_on": "2018-05-11T00:34:03.920465+00:00", "type": "issue", "id": 23}