{"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/12/comments/52846283.json"}, "html": {"href": "#!/labscript_suite/blacs/issues/12#comment-52846283"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs/issues/12.json"}}, "type": "issue", "id": 12, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/blacs.json"}, "html": {"href": "#!/labscript_suite/blacs"}, "avatar": {"href": "data/bytebucket.org/ravatar/{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}ts=249915"}}, "type": "repository", "name": "BLACS", "full_name": "labscript_suite/blacs", "uuid": "{50ed1eb9-8c1b-4afe-a8b8-8e0a33b39a05}"}, "title": "Error not handled well during connection table recompile"}, "content": {"raw": "This is still an issue, I just came across it again \\(seems as though matplotlib is being loaded by labscript which is loaded by runmanager, but matplotlib is trying to use a Qt5 backend on a Qt4 install\\)", "markup": "markdown", "html": "<p>This is still an issue, I just came across it again (seems as though matplotlib is being loaded by labscript which is loaded by runmanager, but matplotlib is trying to use a Qt5 backend on a Qt4 install)</p>", "type": "rendered"}, "created_on": "2019-07-04T07:42:05.833783+00:00", "user": {"display_name": "Shaun Johnstone", "uuid": "{652df738-313d-472c-b7b5-a3f8f98a3322}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D"}, "html": {"href": "https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/38984f1761fc67ce892911496abee619d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSJ-3.png"}}, "nickname": "shjohnst", "type": "user", "account_id": "557058:1b9a15fb-8e4f-407e-b7b9-567c5e1fa1b4"}, "updated_on": null, "type": "issue_comment", "id": 52846283}