{"links": {"self": {"href": "data/repositories/labscript_suite/labscript/issues/17/comments/24650753.json"}, "html": {"href": "#!/labscript_suite/labscript/issues/17#comment-24650753"}}, "issue": {"links": {"self": {"href": "data/repositories/labscript_suite/labscript/issues/17.json"}}, "type": "issue", "id": 17, "repository": {"links": {"self": {"href": "data/repositories/labscript_suite/labscript.json"}, "html": {"href": "#!/labscript_suite/labscript"}, "avatar": {"href": "data/bytebucket.org/ravatar/{48848b08-1db5-463b-bbdc-911beadf8bbf}ts=249917"}}, "type": "repository", "name": "labscript", "full_name": "labscript_suite/labscript", "uuid": "{48848b08-1db5-463b-bbdc-911beadf8bbf}"}, "title": "While setting values for the NI PCI 6733 DAQ..."}, "content": {"raw": "Thanks for the help, Philip. I tried what you suggested, and got a different (but also indecipherable) error.\n\n\n\nTraceback (most recent call last):\n\nFile \"C:\\labscript_suite\\labscript_devices\\NI_PCI_6733.py\", line 233, in transition_to_manual\n\n  self.ao_task.StopTask()\n\n  File \"<string>\", line 3, in StopTask\n\n  File \"<string>\", line 2, in function\n\n  File \"C:\\Anaconda\\lib\\site-packages\\PyDAQmx\\DAQmxFunctions.py\", line 33, in mafunction\n\n raise DAQError(error,errBuff.value.decode(\"utf-8\"), f.__name__)\n\nDAQError: Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.\n\nin function DAQmxStopTask\n\nFatal exception in main process - Tue Jan 12, 12:53:30 :\n\n Traceback (most recent call last):\n\n  File \"C:\\labscript_suite\\blacs\\tab_base_classes.py\", line 670, in mainloop\n\n next_yield = inmain(generator.send,results)\n\n  File \"C:\\Anaconda\\lib\\site-packages\\qtutils\\invoke_in_main.py\", line 68, in inmain\n\n return get_inmain_result(in_main_later(fn,False,*args,**kwargs))\n\n  File \"C:\\Anaconda\\lib\\site-packages\\qtutils\\invoke_in_main.py\", line 47, in event\n\n  result = event.fn(*event.args, **event.kwargs)\n\n  File \"C:\\labscript_suite\\blacs\\device_base_class.py\", line 627, in transition_to_manual\n\nraise Exception('Could not transition to manual. You must restart this device to continue')\n\nException: Could not transition to manual. You must restart this device to continue\n\n\n\nI think the key complaint here is the transition to manual part, but I don't know what that means.\n\n\nRegards\n\nJesse Evans", "markup": "markdown", "html": "<p>Thanks for the help, Philip. I tried what you suggested, and got a different (but also indecipherable) error.</p>\n<p>Traceback (most recent call last):</p>\n<p>File \"C:\\labscript_suite\\labscript_devices\\NI_PCI_6733.py\", line 233, in transition_to_manual</p>\n<p>self.ao_task.StopTask()</p>\n<p>File \"&lt;string&gt;\", line 3, in StopTask</p>\n<p>File \"&lt;string&gt;\", line 2, in function</p>\n<p>File \"C:\\Anaconda\\lib\\site-packages\\PyDAQmx\\DAQmxFunctions.py\", line 33, in mafunction</p>\n<p>raise DAQError(error,errBuff.value.decode(\"utf-8\"), f.<strong>name</strong>)</p>\n<p>DAQError: Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.</p>\n<p>in function DAQmxStopTask</p>\n<p>Fatal exception in main process - Tue Jan 12, 12:53:30 :</p>\n<p>Traceback (most recent call last):</p>\n<p>File \"C:\\labscript_suite\\blacs\\tab_base_classes.py\", line 670, in mainloop</p>\n<p>next_yield = inmain(generator.send,results)</p>\n<p>File \"C:\\Anaconda\\lib\\site-packages\\qtutils\\invoke_in_main.py\", line 68, in inmain</p>\n<p>return get_inmain_result(in_main_later(fn,False,<em>args,</em>*kwargs))</p>\n<p>File \"C:\\Anaconda\\lib\\site-packages\\qtutils\\invoke_in_main.py\", line 47, in event</p>\n<p>result = event.fn(<em>event.args, </em>*event.kwargs)</p>\n<p>File \"C:\\labscript_suite\\blacs\\device_base_class.py\", line 627, in transition_to_manual</p>\n<p>raise Exception('Could not transition to manual. You must restart this device to continue')</p>\n<p>Exception: Could not transition to manual. You must restart this device to continue</p>\n<p>I think the key complaint here is the transition to manual part, but I don't know what that means.</p>\n<p>Regards</p>\n<p>Jesse Evans</p>", "type": "rendered"}, "created_on": "2016-01-12T17:56:54.793273+00:00", "user": {"display_name": "Jesse Evans", "uuid": "{3f9ae0ef-8c02-4174-a140-9c1e3f0c4f31}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3f9ae0ef-8c02-4174-a140-9c1e3f0c4f31%7D"}, "html": {"href": "https://bitbucket.org/%7B3f9ae0ef-8c02-4174-a140-9c1e3f0c4f31%7D/"}, "avatar": {"href": "https://bitbucket.org/account/jcevans/avatar/"}}, "nickname": "jcevans", "type": "user", "account_id": null}, "updated_on": "2016-01-12T18:00:40.610090+00:00", "type": "issue_comment", "id": 24650753}